# Makefile to test ISIS-II simulator on DOS/Win32.
# This assumes that :f1:, :f2:, and :f3: environment variables
# have been previously set up by setup.bat.

ISIS=..\dos\isis

all : run testasm.hex

run : chug
	$(ISIS) chug

chug : chug.obj
	$(ISIS) :f2:link chug.obj,:f2:system.lib,:f2:plm80.lib to chug.lnk
	$(ISIS) :f2:locate chug.lnk to chug
	$(ISIS) chug

chug.obj : chug.plm
	$(ISIS) :f1:plm80 chug.plm

testasm.hex : testasm.obj
	$(ISIS) :f2:objhex testasm.obj to testasm.hex
	type testasm.hex

testasm.obj : testasm.asm
	$(ISIS) :f3:asm80 testasm.asm

clean :
	rm -f *.obj *.lnk *.hex *.lst chug
